# -*- coding: utf-8 -*-
"""Check name & email .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCuVCW5WAly9rDeEhXou1tUOCbQER9oz
"""

def check_name(name):
    if name != " " and not name.isdigit():
        return (1)
    else:
        return (0)

def check_email(email):
  if "@" not in email or "." not in email:
    return 0
  username, domain = email.split("@")
  domainpart1, domainpart2 = domain.split(".")
  if username.isdigit():
            return (0)
  elif username == " ":
            return (0)
  elif  not username.isalnum() :
            return (0)
  elif domainpart1.isdigit():
            return (0)
  elif not domainpart1.isalnum():
            return (0)
  elif domainpart1 == " ":
            return (0)
  elif domainpart1 == "com":
            return (0)
  elif not domainpart2.isalnum() :
           return (0)
  elif domainpart2.isdigit():
            return (0)
  elif domainpart2 == " ":
            return (0)

  else:
       return (1)

while True:
 name = input("enter name ")
 if check_name(name):
      print("valid name")
      break
 else:
      print("invalid name")

while True:
 email = input("enter email ")
 if check_email(email):
      print("valid email")
      break
 else:
      print("invalid email")