# -*- coding: utf-8 -*-
"""check users.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBI6rJdh9hnJs3V15m375lIrEWO_-9dU
"""

list=[{"name":"omar","pass":"123"},{"name":"ahmed","pass":"123"}]
def check_users(user_name, password):
    for i in range(len(list)):
        if list[i]["name"]==user_name:
            if list[i]["pass"]==password:
                return True
            break
    else:
        return False

user_name=input("Enter your name ")
password=input("Enter your password")
if check_users(user_name, password):
        print("welcome")
else:
        print("wrong user_name or password")