# -*- coding: utf-8 -*-
"""Count_Vowels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUCRnNK9VjqkkKPPesv_AkNclFH4dT2G
"""

y = ['a', 'i', 'e', 'o', 'u']

def count_Vowels():
    print("Enter a word:")
    x=input()
    count = 0
    for chr in x:
        if chr in y:
            count += 1

    return count
count = count_Vowels()
print(count)

