# -*- coding: utf-8 -*-
"""mario_pyramid2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185Ulzo1WaXpVUuG5A1spKf5OEbqA-WCl
"""

def mario_pyramid2():
 list=[" "," "," "," "," "]
 for i in range(len(list)):
    list.pop(0)
    list.append("*")
    print(list)

mario_pyramid2()