# -*- coding: utf-8 -*-
"""Mario_pyramid1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MldDYoyM3YteAAgb2SSHIfWrVaE5J5W
"""

def Mario_Pyramid1():
    for i in range(1,5):
       print(" " *(5-i),"*"*i)
