# -*- coding: utf-8 -*-
"""Multiplication_table1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPmne8TnLtAvp8Z2ziXsRih5TFyR7zm2
"""

def multiplication_table1():
    print("Enter Number:")
    x=(input())
    x=int(x)
    for i in range (0, x+1): 
        for j in range (0,x+1):
            print(f"{i}*{j} ={i*j}")
            if j==i:
                break       