# -*- coding: utf-8 -*-
"""multiplication_table2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mc8iuW1BShVra0p7mGzcXq8FTR0dJvGB
"""

def multiplication_table2():
  print("Enter number:")
  n=int(input())
  a=[]
  for i in range(1,n+1):
      list=[]
      for j in range(1,n+1):
          list.append(i*j)
          if(j==i):
              break
      a.append(list)
  print(a)
