# -*- coding: utf-8 -*-
"""Sort numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYuuPh8cimzZg0eHCF5VwW0po0Dn3EqT
"""

def sort_numbers():
    numbers = []
    print("Enter five numbers:")
    for j in range(5):
        number = int(input(f"Numbers {j+1}: ")) # Change variable name to number
        numbers.append(number)  # Append the number to the list
    Ascending = sorted(numbers)
    Descending = sorted(numbers, reverse=True)
    print("Original:", numbers)
    print("Ascending:", Ascending)
    print("Descending:", Descending)

sort_numbers()